const CHEAP = 'cheap';
const EXPENSIVE = 'expensive';

export default {
  VOD: CHEAP,
  IMAGE: CHEAP,
  LINEAR: CHEAP,
  SEARCH: CHEAP,
  PLAY: EXPENSIVE,
  DOWNLOAD: EXPENSIVE,
  AUTHENTICATION: EXPENSIVE,
};
